apiVersion: v1
kind: ConfigMap
metadata:
  name: my.conf
data:
  my.conf: |
    server {
        listen       8080;
        server_name localhost;

        #charset koi8-r;
        #access_log  logs/host.access.log  main;

        listen 443 ssl;

        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        location / {
            root /usr/share/nginx/html;
            add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
            try_files $uri $uri/ /index.html;
            proxy_read_timeout 60s;                  #配置点2，如果没效，可以考虑这个时间配置长一点
            proxy_send_timeout 12s;                  #配置点3
            proxy_set_header Upgrade $http_upgrade; 
            proxy_set_header Connection "Upgrade"; 
          
        }

        location /api {

            proxy_set_header Host $http_host;
            proxy_set_header  X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            rewrite ^/api/(.*)$ /$1 break;  #重写
            proxy_pass http://gva-server:8888; # 设置代理服务器的协议和地址
          

        }

        location /ws {
            proxy_set_header Host $http_host;
            proxy_set_header  X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://gva-server:8888; # 设置代理服务器的协议和地址
            rewrite ^/ws/(.*)$ /$1 break;       
            proxy_set_header Upgrade $http_upgrade; 
            proxy_set_header Connection "Upgrade"; 

        }


        location /tekton-trigger {
            proxy_set_header Host $http_host;
            proxy_set_header  X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            rewrite ^/tekton-trigger/(.*)$ /$1 break;         #重写
            proxy_pass http://el-trigger-listener-smartide-cli:8080;     # 设置代理服务器的协议和地址
         }
     }
