apiVersion: v1
kind: Service
metadata:
  name: gva-web
  annotations:
    flipped-aurora/gin-vue-admin: ui
    github: "https://github.com/flipped-aurora/gin-vue-admin.git"
    app.kubernetes.io/version: 0.0.1
  labels:
    app: gva-web
    version: gva-vue3
spec:
  type: LoadBalancer
  loadBalancerIP: 20.197.100.9
#  type: ClusterIP
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    app: gva-web
    version: gva-vue3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gva-web
  annotations:
    flipped-aurora/gin-vue-admin: ui
    github: "https://github.com/flipped-aurora/gin-vue-admin.git"
    app.kubernetes.io/version: 0.0.1
  labels:
    app: gva-web
    version: gva-vue3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gva-web
      version: gva-vue3
  template:
    metadata:
      labels:
        app: gva-web
        version: gva-vue3
    spec:
      containers:
        - name: gva-web
          image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-web:$(Build.BuildId)
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
            - containerPort: 8080
              name: http
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: nginx-config
            - mountPath: /etc/nginx/ssl
              name: secret-volume
      volumes:
        - name: nginx-config
          configMap:
            name: my.conf
        - name: secret-volume
          secret:
            secretName: nginxsecret
